### PR TITLE
Add missing onnx to requirements

### LINKED ISSUE #40: Missing onnx requirement?
When using the new version of `audonnx` in a CI pipeline I get:

image

### PR DESCRIPTION
**Pull request by hagenw**
Closes #40 

Adds `onnx >=1.8.0` to `install_requires` in `setup.cfg`.

### CODE REVIEW

**Comment by frankenjoe** [comment]
Is it really needed to run a model? And if we add it, should we remove it from `docs/requirements.txt` then?

**Comment by hagenw** [comment]
I don't know if it is needed, but at the moment you cannot import `audonnx` at all:

```python
>>> import audonnx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.8/site-packages/audonnx/__init__.py", line 1, in <module>
    from audonnx.core.api import load
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.8/site-packages/audonnx/core/api.py", line 9, in <module>
    from audonnx.core.model import Model
  File "/home/audeering.local/hwierstorf/.envs/test/lib/python3.8/site-packages/audonnx/core/model.py", line 6, in <module>
    import onnx
ModuleNotFoundError: No module named 'onnx'
```

**Comment by frankenjoe** [comment]
> Is it really needed to run a model? 

Ah it's now needed by the `testing` module.

**Comment by hagenw** [comment]
`onnx.save` is used inside `model.py` and `onnx.ModelProto` for typing.

**Pull request merged**
